### ISSUE TITLE
[Improvement] Hapur Folder Framework

### ISSUE THREAD

**Issue by ad3n** [rajajamal/test-golang-module#1]
Mungkin untuk folder `configs` dan `models` bisa dijadikan root folder dan dikeluarkan dari folder framework sehingga folder framework bisa dihapus

**Comment by rajajamal** [comment]
sudah saya keluarkan mas, juga sudah saya tambahkan .env. Kalau lihat dari vscode codingnya ga ada yg error lagi. pas eksekusi main.go keluar pesan gini 
[error] failed to initialize database, got error dial tcp [::1]:3306: connectex: No connection could be made because the target machine actively refused it.    
panic: dial tcp [::1]:3306: connectex: No connection could be made because the target machine actively refused it.

**Comment by ad3n** [comment]
Untuk mysql-nya sudah diinstall mas?

**Comment by rajajamal** [comment]
udah mas

**Comment by ad3n** [comment]
Sepertinya itu ga bisa remote connection Pak, coba env-nya diupload juga Pak

**Comment by ad3n** [comment]
mas @rajajamal coba jalankan perintah `mysql -uroot -paden course` hasilnya nanti di-SS di sini ya mas

**Comment by rajajamal** [comment]
mysql : The term 'mysql' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mysql -uroot -paden course
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (mysql:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rajajamal** [comment]
sepertinya memang karena mysql belum terinstal mas, cuma install driver aja kemarin. baru ingat saya ga pake docker, jadi mesti intall di mesin langsung

**Comment by rajajamal** [comment]
Error 1046: No database selected
[0.000ms] [rows:0] CREATE TABLE `users` (`id` bigint AUTO_INCREMENT,`username` longtext,`password` longtext,PRIMARY KEY (`id`))

 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.34.1                   │
 │               http://127.0.0.1:3000               │
 │       (bound on host 0.0.0.0 and port 3000)       │
 │                                                   │
 │ Handlers ............. 2  Processes ........... 1 │
 │ Prefork ....... Disabled  PID .............. 7328 │
 └───────────────────────────────────────────────────┘ 


sudah bisa mas

**Comment by ad3n** [comment]
Mantap mas
